### ISSUE TITLE
Task-8: Column Standardization

### ISSUE THREAD

**Issue by himanshu370** [opencodeiiita/LiblessML#20]
In this task you have to write a function for **Column Standardization**. You can only use **Numpy** and **Pandas** to write the function.

The function will go as follows:

def column_standardization (column_name, dataframe)
"
write your code here
"

What is **Column Standardization**? You can check it [here](https://towardsdatascience.com/how-and-why-to-standardize-your-data-996926c2c832)

**Comment by osho-20** [comment]
claim
