### ISSUE TITLE
Task 1 : Balancing data after dropping null values

### ISSUE THREAD

**Issue by pSN0W** [opencodeiiita/LiblessML#4]
You are given a data set named open_code.csv. The dataset is unbalanced as well as contains null values. You are supposed to remove the rows containing null values and repeat the minority class to balance the dataset.
You are provided with a notebook that you can download along with the task. The notebook contains all the steps you need to follow to complete this task.

**Comment by anshumanjain2010** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
I want to claim this issue.

**Comment by pSN0W** [comment]
> claim

The issue has been given to @anshumanjain2010.

**Comment by rushilpatra** [comment]
claim

**Comment by pSN0W** [comment]
> I want to claim this issue.

The issue is assigned to @Pranav-22-aditya

**Comment by pSN0W** [comment]
> claim

This issue is assigned to @anshumanjain2010

**Comment by janhaviiii** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by DeepMechatronics** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by baruni07** [comment]
claim

**Comment by MaqsudMallick** [comment]
claim

**Comment by himanshu370** [comment]
> claim

@baruni07 This task was not assigned to you, Hence, your notebook will not be checked.

**Comment by anshumanjain2010** [comment]
https://colab.research.google.com/drive/1EWYm4qchHlczpLpIX4vI0joFcL9pLFHr?usp=sharing

**Comment by anshumanjain2010** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by pSN0W** [comment]
> https://colab.research.google.com/drive/1EWYm4qchHlczpLpIX4vI0joFcL9pLFHr?usp=sharing

The solution is correct
You can view the solution provided by @anshumanjain2010 <a href="https://github.com/opencodeiiita/LiblessML/blob/main/Task1/task_1_assignee_sol.ipynb">here</a>
You can view the solution propsed by mentors <a href="https://github.com/opencodeiiita/LiblessML/blob/main/Task1/task_1_sol.ipynb">here</a>

**Comment by pSN0W** [comment]
This issue is closed now.
Points awarded to @anshumanjain2010
