### ISSUE TITLE
Task 2 : One Hot Encoding

### ISSUE THREAD

**Issue by pSN0W** [opencodeiiita/LiblessML#5]
You are given another csv file named open_code_2.csv. You are provided with a notebook which contains all the steps required to complete this task.
Basically what you have to do is load the data set. Look for the column named ‘category’. Check for the value counts of each category of column named 'category'. Check for such classes whose value count is less than 25. Put them all under a new category named ‘other_category’. Then apply one hot encoding to the column ‘category’.

**Comment by anshumanjain2010** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
I want to claim this issue.

**Comment by Aneesh02** [comment]
claim

**Comment by pSN0W** [comment]
> claim

The issue is assigned to @Aneesh02

**Comment by rushilpatra** [comment]
claim

**Comment by pSN0W** [comment]
> I want to claim this issue.

The issue is assigned to @Pranav-22-aditya

**Comment by pSN0W** [comment]
> claim

This issue is assigned to @anshumanjain2010

**Comment by pSN0W** [comment]
> I want to claim this issue.

This issue is assigned to @Pranav-22-aditya

**Comment by janhaviiii** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by aviralgupta752** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by baruni07** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by AnushaNathRoy** [comment]
claim

**Comment by baruni07** [comment]
there is a bug in cell UNIQUE 6:
**df = pd.concat([changed_col_df,df])** should be changed to **df = pd.concat([changed_col_df,df], axis = 1)**
since the rows are getting added twice instead of columns

**Comment by Pranav-22-aditya** [comment]
https://colab.research.google.com/drive/1Z02UznZXQIk2_5wuFkX70yVyCZwy_pJg?usp=sharing
this is the answer of task2 assigned to me

**Comment by pSN0W** [comment]
> there is a bug in cell UNIQUE 6: **df = pd.concat([changed_col_df,df])** should be changed to **df = pd.concat([changed_col_df,df], axis = 1)** since the rows are getting added twice instead of columns

Thank You for mentioning it. The bug has been removed

**Comment by pSN0W** [comment]
> https://colab.research.google.com/drive/1Z02UznZXQIk2_5wuFkX70yVyCZwy_pJg?usp=sharing this is the answer of task2 assigned to me

@Pranav-22-aditya your notebook though being correct and satisfying this task does not follow the basic rules of clean code. Many values have been hard coded which defeats the concept of reusing code as well as learning. 
Hard coding the values won't work for data set much larger. If we add new data points to this data set the whole process of data pre processing would have to be done again which is a tedious and extravagant work.
Due to the above specified reason we can not accept this notebook as solution for this task.
You can re submit your work until you reach your deadline.

**Comment by rushilpatra** [comment]
claim

**Comment by anshumanjain2010** [comment]
claim

**Comment by Aneesh02** [comment]
claim

**Comment by pSN0W** [comment]
<b>This issue is open to claim now</b>

**Comment by Monik09** [comment]
claim

**Comment by Aneesh02** [comment]
claim

**Comment by Aneesh02** [comment]
> claim

I claimed once you unassigned

**Comment by pSN0W** [comment]
> claim

Issue assigned to @Monik09

**Comment by pSN0W** [comment]
> > claim
> 
> I claimed once you unassigned

We considered claims after the notice is provided here as well as on discord. Better luck next time :)
Good Job on Task 3 by the way <3

**Comment by baruni07** [comment]
i want to claim . i have finished the task just need to be assigned to upload it

**Comment by himanshu370** [comment]
> i want to claim . i have finished the task just need to be assigned to upload it

This task is already assigned to @Monik09.
