### ISSUE TITLE
Task 3 : Basic Featurization

### ISSUE THREAD

**Issue by pSN0W** [opencodeiiita/LiblessML#6]
You are given a csv file named open_code_2.csv.
You have to do featurisation of column named 'installs','price' and 'size'. Basic knowledge of string manipulation and pandas is enough to complete this task.
You are provided with a notebook that will help you through this task.

**Comment by Aneesh02** [comment]
claim

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by rushilpatra** [comment]
claim

**Comment by rushilpatra** [comment]
claim

**Comment by anshumanjain2010** [comment]
claim

**Comment by pSN0W** [comment]
> claim

This issue is assigned to @rushilpatra

**Comment by pSN0W** [comment]
> claim

This issue is assigned to @Aneesh02

**Comment by Aneesh02** [comment]
@pSN0W Thanks! Looking forward to working on this issue

**Comment by janhaviiii** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by souvenger** [comment]
claim

**Comment by aviralgupta752** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by AnushaNathRoy** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by Aneesh02** [comment]
@pSN0W 
https://colab.research.google.com/drive/1JejvTF-nfnIYpYOv2CPWqFa3bcn7Hy1R?usp=sharing

**Comment by anshumanjain2010** [comment]
claim

**Comment by pSN0W** [comment]
> @pSN0W https://colab.research.google.com/drive/1JejvTF-nfnIYpYOv2CPWqFa3bcn7Hy1R?usp=sharing

The solution provided by @Aneesh02 is correct.
You can view his solution <a href="https://github.com/opencodeiiita/LiblessML/blob/main/Task3/task_3_assignee_sol.ipynb">here</a>
You can view the solution provided by mentor <a href="https://github.com/opencodeiiita/LiblessML/blob/main/Task3/task_3_sol.ipynb">here</a>

**Comment by pSN0W** [comment]
The issue is closed now.
Points provided to @Aneesh02 .
